# This is almost fully copy-pasted file from Docker Hub.
# Working only on my local instance of the app.
# Definitely will not move into production like this.
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'employee-manager'
#      MYSQL_USER: 'root'
#      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3305:3306'
    expose:
      - '3306'